# ═══════════════════════════════════════════════════════════════
# Kisan Store — r/farm_analytics.R
# Farm reward analytics in R (base R only — no packages needed).
# Analyses the SAME catalog the website uses (via data/catalog.tsv,
# generated by scripts/gen_tsv.py) and simulates farmer behaviour.
#
#   Rscript r/farm_analytics.R
# ═══════════════════════════════════════════════════════════════

# ── Reward rules (mirror of data/catalog.json → rewards) ──
DAILY_CHECKIN_COINS   <- 5
MIN_PHOTOS            <- 3
MIN_VIDEO_SECONDS     <- 5
MIN_DESCRIPTION_CHARS <- 10
STARTING_BALANCE      <- 1250

find_tsv <- function() {
  candidates <- c(
    "data/catalog.tsv",
    "../data/catalog.tsv",
    "../../data/catalog.tsv"
  )
  hit <- candidates[file.exists(candidates)]
  if (length(hit) == 0) {
    stop("data/catalog.tsv not found — run: python3 scripts/gen_tsv.py")
  }
  hit[1]
}

cat("\n┌─────────────────────────────────────────────────────────────┐\n")
cat("│  🌱 Kisan Store — R Analytics (base R)                     │\n")
cat("│  Data-for-Equipment — Empowering every farmer              │\n")
cat("└─────────────────────────────────────────────────────────────┘\n")

catalog <- read.delim(find_tsv(), sep = "\t", stringsAsFactors = FALSE,
                      na.strings = c("", "NA"))
cat(sprintf("  Loaded %d products from data/catalog.tsv\n", nrow(catalog)))

# ── Category summary: avg price, total redeemed ──
cat("\n  📊 Category summary:\n")
agg <- aggregate(price ~ category, data = catalog,
                 FUN = function(x) round(mean(x), 0))
names(agg) <- c("Category", "AvgPrice")
agg$TotalRedeemed <- tapply(catalog$redeemed, catalog$category, sum)[agg$Category]
agg$Products <- table(catalog$category)[agg$Category]
agg <- agg[order(-agg$TotalRedeemed), ]
print(agg, row.names = FALSE)

# ── Offers ──
offers <- catalog[!is.na(catalog$oldPrice) & catalog$oldPrice > catalog$price, ]
cat(sprintf("\n  🏷️  Active offers: %d\n", nrow(offers)))
if (nrow(offers) > 0) {
  offers$discount <- round((1 - offers$price / offers$oldPrice) * 100, 0)
  print(offers[, c("name", "price", "oldPrice", "discount")], row.names = FALSE)
}

# ── Farmer simulation: 30 / 90 / 200 days of check-ins ──
cat("\n  📷 Farmer simulation (5 coins per daily check-in):\n")
for (days in c(30, 90, 200)) {
  balance <- STARTING_BALANCE + days * DAILY_CHECKIN_COINS
  affordable <- sum(catalog$price <= balance)
  cat(sprintf("     %3d days → %4d coins → can redeem %2d/%d products\n",
              days, balance, affordable, nrow(catalog)))
}

# ── How many days until each product is free? ──
cat("\n  ⏳ Days of check-ins until each reward is free (from 1250 coins):\n")
catalog$daysNeeded <- ceiling(pmax(0, catalog$price - STARTING_BALANCE) / DAILY_CHECKIN_COINS)
plan <- catalog[order(catalog$daysNeeded), c("name", "price", "daysNeeded")]
print(plan, row.names = FALSE)

# ── Top 5 most redeemed (community favourites) ──
cat("\n  🔥 Top 5 most redeemed rewards:\n")
top <- catalog[order(-catalog$redeemed), ][1:5, c("name", "redeemed", "rating")]
print(top, row.names = FALSE)

# ── Rating distribution ──
cat("\n  ⭐ Rating distribution:\n")
print(table(cut(catalog$rating, breaks = seq(4.0, 5.0, by = 0.2),
                include.lowest = TRUE)))

cat("\n  ✅ Analysis complete — Jai Kisan! 🌾\n\n")
